test: &default

  # Credentials for REST APIs
  client_id: ARPnYxDGlzBp3vRyaRPIjEOSVyCVEMPhWFK6qGboJfzaCycz3NNp8GeES2fc
  client_secret: ECaNHBDqkIARcjhJCdgGI5btCXNjy2Z-z0N9DQl8bJLSi6thOf2BCU6tB56j

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: nickslist1-facilitator_api1.hotmail.com
  password: 1381923907
  signature: AY.g67JVldhOGe.gw7Ljl.nR50MDAXtNpxJ3ZeUt2HPbPVrHsD2gBIuY
  

  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: nickslist1-facilitator@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default
  mode: sandbox
  
production:
  <<: *default
  mode: live
